name: weather_report

on:
  schedule:
    - cron: '0 22 * * *' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Execute Rake task
      run: 
        bundle exec rake send_weather_report
      env:
        END_POINT_URL: ${{ secrets.END_POINT_URL }}
